/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz_gráfica;

import UserAccount.UserAccount;
import db_connection.DBConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;
import de.mkammerer.argon2.Argon2;
import de.mkammerer.argon2.Argon2Factory;
import java.awt.Color;

/**
 *
 * @author TomasUcu
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Home() {
        initComponents();
    }

    public static Home instance;

    public static Home getInstance() {
        if (instance == null) {
            instance = new Home();
        }
        return instance;
    }
    
    public static void closeInstance() {
        instance = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        topBg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        logOutBtn = new javax.swing.JPanel();
        logOutTxt1 = new javax.swing.JLabel();
        AU_Btn = new javax.swing.JPanel();
        changePasswordTxt = new javax.swing.JLabel();
        GIP_Btn = new javax.swing.JPanel();
        viewRolesTxt = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        subTitle1 = new javax.swing.JLabel();
        subTitle2 = new javax.swing.JLabel();
        D_Btn = new javax.swing.JPanel();
        logOutTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setSize(getPreferredSize());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topBg.setBackground(new java.awt.Color(51, 153, 255));
        topBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Calisto MT", 0, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Bienvenido a");
        topBg.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 152, 261, 71));

        title2.setFont(new java.awt.Font("Calisto MT", 0, 36)); // NOI18N
        title2.setForeground(new java.awt.Color(255, 255, 255));
        title2.setText("gestión de permisos");
        topBg.add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 256, -1, 88));

        logOutBtn.setBackground(new java.awt.Color(51, 153, 255));
        logOutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutBtnMouseExited(evt);
            }
        });

        logOutTxt1.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        logOutTxt1.setForeground(new java.awt.Color(0, 0, 0));
        logOutTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logOutTxt1.setText("Cerrar sesión");

        javax.swing.GroupLayout logOutBtnLayout = new javax.swing.GroupLayout(logOutBtn);
        logOutBtn.setLayout(logOutBtnLayout);
        logOutBtnLayout.setHorizontalGroup(
            logOutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logOutTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        logOutBtnLayout.setVerticalGroup(
            logOutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logOutTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        topBg.add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        bg.add(topBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 570));

        AU_Btn.setBackground(new java.awt.Color(51, 153, 255));
        AU_Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AU_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AU_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AU_BtnMouseClicked(evt);
            }
        });

        changePasswordTxt.setBackground(new java.awt.Color(51, 153, 255));
        changePasswordTxt.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        changePasswordTxt.setForeground(new java.awt.Color(255, 255, 255));
        changePasswordTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changePasswordTxt.setText("Autoregistro de Usuarios");

        javax.swing.GroupLayout AU_BtnLayout = new javax.swing.GroupLayout(AU_Btn);
        AU_Btn.setLayout(AU_BtnLayout);
        AU_BtnLayout.setHorizontalGroup(
            AU_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(changePasswordTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AU_BtnLayout.setVerticalGroup(
            AU_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(changePasswordTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        bg.add(AU_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 300, 80));

        GIP_Btn.setBackground(new java.awt.Color(51, 153, 255));
        GIP_Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GIP_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GIP_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GIP_BtnMouseClicked(evt);
            }
        });

        viewRolesTxt.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        viewRolesTxt.setForeground(new java.awt.Color(255, 255, 255));
        viewRolesTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewRolesTxt.setText("Gestion de Identidades y Permisos");

        javax.swing.GroupLayout GIP_BtnLayout = new javax.swing.GroupLayout(GIP_Btn);
        GIP_Btn.setLayout(GIP_BtnLayout);
        GIP_BtnLayout.setHorizontalGroup(
            GIP_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewRolesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );
        GIP_BtnLayout.setVerticalGroup(
            GIP_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewRolesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        bg.add(GIP_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 300, 80));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnMouseExited(evt);
            }
        });

        exitTxt.setBackground(new java.awt.Color(0, 0, 0));
        exitTxt.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        exitTxt.setForeground(new java.awt.Color(0, 0, 0));
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        bg.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, -1));

        subTitle1.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        subTitle1.setForeground(new java.awt.Color(0, 0, 0));
        subTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle1.setText("Seleccione la aplicación sobre ");
        bg.add(subTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 330, 40));

        subTitle2.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        subTitle2.setForeground(new java.awt.Color(0, 0, 0));
        subTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle2.setText("la cual quiere gestionar");
        bg.add(subTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        D_Btn.setBackground(new java.awt.Color(51, 153, 255));
        D_Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        D_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        D_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D_BtnMouseClicked(evt);
            }
        });

        logOutTxt.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        logOutTxt.setForeground(new java.awt.Color(255, 255, 255));
        logOutTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logOutTxt.setText("Dummy");

        javax.swing.GroupLayout D_BtnLayout = new javax.swing.GroupLayout(D_Btn);
        D_Btn.setLayout(D_BtnLayout);
        D_BtnLayout.setHorizontalGroup(
            D_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logOutTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        D_BtnLayout.setVerticalGroup(
            D_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logOutTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        bg.add(D_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 300, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        exitBtn.setBackground(Color.red);
    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseExited
        exitBtn.setBackground(Color.white);
    }//GEN-LAST:event_exitBtnMouseExited

    private void AU_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AU_BtnMouseClicked
        this.setVisible(false);
        Permisos_AU.getInstance().setVisible(true);
    }//GEN-LAST:event_AU_BtnMouseClicked

    private void D_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D_BtnMouseClicked
        this.setVisible(false);
        Permisos_Dummy.getInstance().setVisible(true);
    }//GEN-LAST:event_D_BtnMouseClicked

    int xMouse, yMouse; 
    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void GIP_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GIP_BtnMouseClicked
        this.setVisible(false);
        Permisos_GestionPermisos.getInstance().setVisible(true);
    }//GEN-LAST:event_GIP_BtnMouseClicked

    private void logOutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseClicked
        UserAccount.getInstance().setUserId(0);
        this.setVisible(false);
        closeInstance();
        Login.getInstance().setVisible(true);
    }//GEN-LAST:event_logOutBtnMouseClicked

    private void logOutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseEntered
        logOutBtn.setBackground(Color.red);
    }//GEN-LAST:event_logOutBtnMouseEntered

    private void logOutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseExited
        logOutBtn.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_logOutBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AU_Btn;
    private javax.swing.JPanel D_Btn;
    private javax.swing.JPanel GIP_Btn;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel changePasswordTxt;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JPanel logOutBtn;
    private javax.swing.JLabel logOutTxt;
    private javax.swing.JLabel logOutTxt1;
    private javax.swing.JLabel subTitle1;
    private javax.swing.JLabel subTitle2;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title2;
    private javax.swing.JPanel topBg;
    private javax.swing.JLabel viewRolesTxt;
    // End of variables declaration//GEN-END:variables
}
