/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz_gráfica;

import UserAccount.UserAccount;
import db_connection.DBConnection;
import java.sql.Connection;
import java.sql.Statement;
import java.util.Dictionary;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.LinkedList;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author TomasUcu
 */
public class ApplicationRegisterQuestions extends javax.swing.JFrame {

    public static ApplicationRegisterQuestions instance;
    private Map<String, Integer> preguntasId;

    public static ApplicationRegisterQuestions getInstance() {
        if (instance == null) {
            instance = new ApplicationRegisterQuestions();
        }
        return instance;
    }

    public ApplicationRegisterQuestions() {
        initComponents();
        Connection connection = DBConnection.getInstance().dbConnection;
        Statement statement = null;

        try {
            statement = connection.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al crear statement, error: " + e.toString());
        }

        preguntasId = new HashMap<String, Integer>();

        if (statement != null) {
            try {
                String sqlString = "SELECT * "
                        + "FROM PREGUNTAS";
                var res = statement.executeQuery(sqlString);
                while (res.next()) {
                    String pregunta = res.getString("pregunta");
                    Integer id = res.getInt("preg_id");
                    preguntasId.put(pregunta, id);
                }
                Pregunta1.setModel(new DefaultComboBoxModel<String>(preguntasId.keySet().toArray(new String[0])));
                Pregunta2.setModel(new DefaultComboBoxModel<String>(preguntasId.keySet().toArray(new String[0])));
                Pregunta3.setModel(new DefaultComboBoxModel<String>(preguntasId.keySet().toArray(new String[0])));

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro al obtener user, error: " + e.toString());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Pregunta1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Pregunta2 = new javax.swing.JComboBox<>();
        Pregunta3 = new javax.swing.JComboBox<>();
        Respuesta1 = new javax.swing.JTextField();
        Respuesta2 = new javax.swing.JTextField();
        Respuesta3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setSize(new java.awt.Dimension(450, 600));

        Pregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pregunta1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Preguntas");

        Pregunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pregunta2ActionPerformed(evt);
            }
        });

        Pregunta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pregunta3ActionPerformed(evt);
            }
        });

        Respuesta1.setText("Respuesta");
        Respuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Respuesta1ActionPerformed(evt);
            }
        });

        Respuesta2.setText("Respuesta");

        Respuesta3.setText("Respuesta");

        jButton2.setText("Registrarse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Pregunta3, javax.swing.GroupLayout.Alignment.LEADING, 0, 251, Short.MAX_VALUE)
                        .addComponent(Pregunta1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pregunta2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Respuesta1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Respuesta2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Respuesta3, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(93, 93, 93)))
                .addContainerGap(473, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(Pregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Respuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(Pregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Respuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Pregunta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Respuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Pregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pregunta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pregunta1ActionPerformed

    private void Pregunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pregunta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pregunta2ActionPerformed

    private void Pregunta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pregunta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pregunta3ActionPerformed

    private void Respuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Respuesta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Respuesta1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String pregunta1 = Pregunta1.getSelectedItem().toString();
        String pregunta2 = Pregunta2.getSelectedItem().toString();
        String pregunta3 = Pregunta3.getSelectedItem().toString();

        String respuesta1 = Respuesta1.getText();
        String respuesta2 = Respuesta2.getText();
        String respuesta3 = Respuesta3.getText();

        if (pregunta1.equals(pregunta2) | pregunta1.equals(pregunta3) | pregunta2.equals(pregunta3)) {
            JOptionPane.showMessageDialog(null, "Debe elegir preguntas diferentes.");
            return;
        } else if (respuesta1.isEmpty() | respuesta2.isEmpty() | respuesta3.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Las respuestas no pueden estar vacias.");
            return;
        }

        Connection connection = DBConnection.getInstance().dbConnection;

        Statement statement = null;
        try {
            statement = connection.createStatement();
            if (statement != null) {
                String sqlStringPreg1 = "INSERT INTO PERSONAS_PREGUNTAS (user_id, preg_id, respuesta) "
                        + "VALUES (" + UserAccount.getInstance().userId + ", " + preguntasId.get(pregunta1.toString()) + ", '" + respuesta1.toString() + "')";
                
                String sqlStringPreg2 = "INSERT INTO PERSONAS_PREGUNTAS (user_id, preg_id, respuesta) "
                        + "VALUES (" + UserAccount.getInstance().userId + ", " + preguntasId.get(pregunta2.toString()) + ", '" + respuesta2.toString() + "')";
                
                String sqlStringPreg3 = "INSERT INTO PERSONAS_PREGUNTAS (user_id, preg_id, respuesta) "
                        + "VALUES (" + UserAccount.getInstance().userId + ", " + preguntasId.get(pregunta3.toString()) + ", '" + respuesta3.toString() + "')";
                
                statement.executeUpdate(sqlStringPreg1);
                statement.executeUpdate(sqlStringPreg2);
                statement.executeUpdate(sqlStringPreg3);
                
                this.setVisible(false);
                ChangePassword.getInstance().setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro al agregar user, error: " + e.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Pregunta1;
    private javax.swing.JComboBox<String> Pregunta2;
    private javax.swing.JComboBox<String> Pregunta3;
    private javax.swing.JTextField Respuesta1;
    private javax.swing.JTextField Respuesta2;
    private javax.swing.JTextField Respuesta3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton registrarse;
    private javax.swing.JButton registrarse1;
    private javax.swing.JButton registrarse2;
    private javax.swing.JButton registrarse3;
    private javax.swing.JButton registrarse4;
    private javax.swing.JButton registrarse5;
    // End of variables declaration//GEN-END:variables
}
