/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz_gráfica;

import db_connection.DBConnection;
import de.mkammerer.argon2.Argon2;
import de.mkammerer.argon2.Argon2Factory;
import java.sql.Connection;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;
import UserAccount.UserAccount;

/**
 *
 * @author TomasUcu
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ApplicationAccount
     */
    public ChangePassword() {
        initComponents();
    }

    public static ChangePassword instance;

    public static ChangePassword getInstance() {
        if (instance == null) {
            instance = new ChangePassword();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombres = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        passwordToChange = new javax.swing.JTextField();
        passwordToChangeConfirm = new javax.swing.JTextField();
        cambiarHandler = new javax.swing.JButton();

        nombres.setText("Nombres");
        nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresActionPerformed(evt);
            }
        });

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cambiar Contraseña");

        passwordToChange.setText("Nueva Contraseña");
        passwordToChange.setToolTipText("");
        passwordToChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordToChangeActionPerformed(evt);
            }
        });

        passwordToChangeConfirm.setText("Confirmar Contraseña");
        passwordToChangeConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordToChangeConfirmMouseClicked(evt);
            }
        });
        passwordToChangeConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordToChangeConfirmActionPerformed(evt);
            }
        });

        cambiarHandler.setText("Cambiar");
        cambiarHandler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarHandlerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordToChangeConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordToChange, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addComponent(cambiarHandler, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passwordToChange, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(passwordToChangeConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cambiarHandler, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        passwordToChangeConfirm.getAccessibleContext().setAccessibleName("");
        passwordToChangeConfirm.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresActionPerformed

    private void passwordToChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordToChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordToChangeActionPerformed

    private void passwordToChangeConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordToChangeConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordToChangeConfirmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cambiarHandlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarHandlerActionPerformed
        String password = passwordToChange.getText();
        String passwordConfirm = passwordToChangeConfirm.getText();

        Argon2 argon2 = Argon2Factory.create(Argon2Factory.Argon2Types.ARGON2id, 32, 64);
        Connection connection = DBConnection.getInstance().dbConnection;
        Statement statement = null;
        try {
            if (password.equals(passwordConfirm)) {
                var hashPass = argon2.hash(2, 15 * 1024, 1, password.toCharArray());

                statement = connection.createStatement();
                if (statement != null) {
                    String sqlString
                            = "UPDATE PERSONAS "
                            + "SET hashpwd='" + hashPass + "' "
                            + "WHERE user_id=" + UserAccount.getInstance().userId;
                    System.out.println(sqlString);
                    int rs = statement.executeUpdate(sqlString);
                    if (rs == 1) {
                        JOptionPane.showMessageDialog(null, "Cambio contraseña con éxito");
                    } else {
                        JOptionPane.showMessageDialog(null, "Problema al cambiar la contraseña. Prueba otra vez.");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Contraseñas no coinciden.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro al cambiar la contraseña, error: " + e.toString());
        }

    }//GEN-LAST:event_cambiarHandlerActionPerformed

    private void passwordToChangeConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordToChangeConfirmMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordToChangeConfirmMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarHandler;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombres;
    private javax.swing.JTextField passwordToChange;
    private javax.swing.JTextField passwordToChangeConfirm;
    // End of variables declaration//GEN-END:variables
}
