/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz_gráfica;

import db_connection.DBConnection;
import de.mkammerer.argon2.Argon2;
import de.mkammerer.argon2.Argon2Factory;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import UserAccount.UserAccount;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author TomasUcu
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form AppRegister
     */
    public Register() {
        initComponents();
    }

    public static Register instance;

    public static Register getInstance() {
        if (instance == null) {
            instance = new Register();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        goBackBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        confirmPasswordText = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        bgImage = new javax.swing.JLabel();
        nombreUsuarioText = new javax.swing.JLabel();
        apellidosText = new javax.swing.JLabel();
        direccionText = new javax.swing.JLabel();
        ciudadText = new javax.swing.JLabel();
        departamentoText = new javax.swing.JLabel();
        contraseñaText = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lastNameInput = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        addressInput = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        cityInput = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        departamentoInput = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        confirmPasswordInput = new javax.swing.JPasswordField();
        passwordInput = new javax.swing.JPasswordField();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        continueBtn = new javax.swing.JPanel();
        continueTxt = new javax.swing.JLabel();
        nombresText = new javax.swing.JLabel();
        userNameInput = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        goBackBtn.setBackground(new java.awt.Color(75, 181, 255));
        goBackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                goBackBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                goBackBtnMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<");

        javax.swing.GroupLayout goBackBtnLayout = new javax.swing.GroupLayout(goBackBtn);
        goBackBtn.setLayout(goBackBtnLayout);
        goBackBtnLayout.setHorizontalGroup(
            goBackBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        goBackBtnLayout.setVerticalGroup(
            goBackBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(goBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        confirmPasswordText.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        confirmPasswordText.setForeground(new java.awt.Color(0, 0, 0));
        confirmPasswordText.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        confirmPasswordText.setText("Confirmar contraseña");
        jPanel1.add(confirmPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        title1.setFont(new java.awt.Font("Calisto MT", 3, 40)); // NOI18N
        title1.setForeground(new java.awt.Color(0, 0, 0));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("Registrese");
        jPanel1.add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 240, 130));

        title2.setFont(new java.awt.Font("Calisto MT", 3, 40)); // NOI18N
        title2.setForeground(new java.awt.Color(0, 0, 0));
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("Aquí");
        jPanel1.add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 130));

        bgImage.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bgImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan-\\OneDrive - Universidad Católica del Uruguay\\UCU\\2do\\2do semestre\\BD I\\bd-obligatorio\\Images\\Auto-Registro\\fondoRegister.jpg")); // NOI18N
        jPanel1.add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 570));

        nombreUsuarioText.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        nombreUsuarioText.setForeground(new java.awt.Color(0, 0, 0));
        nombreUsuarioText.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nombreUsuarioText.setText("Nombre de usuario");
        jPanel1.add(nombreUsuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 130, -1));

        apellidosText.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        apellidosText.setForeground(new java.awt.Color(0, 0, 0));
        apellidosText.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        apellidosText.setText("Apellidos");
        jPanel1.add(apellidosText, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        direccionText.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        direccionText.setForeground(new java.awt.Color(0, 0, 0));
        direccionText.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        direccionText.setText("Dirección");
        jPanel1.add(direccionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        ciudadText.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        ciudadText.setForeground(new java.awt.Color(0, 0, 0));
        ciudadText.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ciudadText.setText("Ciudad");
        jPanel1.add(ciudadText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 50, -1));

        departamentoText.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        departamentoText.setForeground(new java.awt.Color(0, 0, 0));
        departamentoText.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        departamentoText.setText("Departamento");
        jPanel1.add(departamentoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        contraseñaText.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        contraseñaText.setForeground(new java.awt.Color(0, 0, 0));
        contraseñaText.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        contraseñaText.setText("Contraseña");
        jPanel1.add(contraseñaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 80, -1));

        nameInput.setBackground(new java.awt.Color(255, 255, 255));
        nameInput.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        nameInput.setForeground(new java.awt.Color(153, 153, 153));
        nameInput.setText("Ingrese su nombre/s");
        nameInput.setBorder(null);
        nameInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nameInputMousePressed(evt);
            }
        });
        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });
        jPanel1.add(nameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 290, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 260, 10));

        lastNameInput.setBackground(new java.awt.Color(255, 255, 255));
        lastNameInput.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        lastNameInput.setForeground(new java.awt.Color(153, 153, 153));
        lastNameInput.setText("Ingrese sus apellidos");
        lastNameInput.setBorder(null);
        lastNameInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lastNameInputMousePressed(evt);
            }
        });
        lastNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameInputActionPerformed(evt);
            }
        });
        jPanel1.add(lastNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 290, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 260, 10));

        addressInput.setBackground(new java.awt.Color(255, 255, 255));
        addressInput.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        addressInput.setForeground(new java.awt.Color(153, 153, 153));
        addressInput.setText("Ingrese su dirección");
        addressInput.setBorder(null);
        addressInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressInputMouseClicked(evt);
            }
        });
        addressInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressInputActionPerformed(evt);
            }
        });
        jPanel1.add(addressInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 290, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 260, 10));

        cityInput.setBackground(new java.awt.Color(255, 255, 255));
        cityInput.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        cityInput.setForeground(new java.awt.Color(153, 153, 153));
        cityInput.setText("Ingrese su ciudad");
        cityInput.setBorder(null);
        cityInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cityInputMousePressed(evt);
            }
        });
        cityInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityInputActionPerformed(evt);
            }
        });
        jPanel1.add(cityInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 290, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 260, 10));

        departamentoInput.setBackground(new java.awt.Color(255, 255, 255));
        departamentoInput.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        departamentoInput.setForeground(new java.awt.Color(153, 153, 153));
        departamentoInput.setText("Ingrese su departamento");
        departamentoInput.setBorder(null);
        departamentoInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                departamentoInputMousePressed(evt);
            }
        });
        departamentoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentoInputActionPerformed(evt);
            }
        });
        jPanel1.add(departamentoInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 290, 20));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 260, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 260, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 260, 10));

        confirmPasswordInput.setBackground(new java.awt.Color(255, 255, 255));
        confirmPasswordInput.setForeground(new java.awt.Color(153, 153, 153));
        confirmPasswordInput.setText("**********");
        confirmPasswordInput.setBorder(null);
        confirmPasswordInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmPasswordInputMousePressed(evt);
            }
        });
        jPanel1.add(confirmPasswordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 260, 20));

        passwordInput.setBackground(new java.awt.Color(255, 255, 255));
        passwordInput.setForeground(new java.awt.Color(153, 153, 153));
        passwordInput.setText("**********");
        passwordInput.setBorder(null);
        passwordInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordInputMousePressed(evt);
            }
        });
        jPanel1.add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 260, 20));

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnMouseExited(evt);
            }
        });

        exitTxt.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        exitTxt.setForeground(new java.awt.Color(0, 0, 0));
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 30, 30));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        continueBtn.setBackground(new java.awt.Color(89, 191, 255));
        continueBtn.setForeground(new java.awt.Color(89, 191, 255));
        continueBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continueBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continueBtnMouseClicked(evt);
            }
        });

        continueTxt.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        continueTxt.setForeground(new java.awt.Color(255, 255, 255));
        continueTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        continueTxt.setText("Continuar");

        javax.swing.GroupLayout continueBtnLayout = new javax.swing.GroupLayout(continueBtn);
        continueBtn.setLayout(continueBtnLayout);
        continueBtnLayout.setHorizontalGroup(
            continueBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(continueTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        continueBtnLayout.setVerticalGroup(
            continueBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(continueTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(continueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 170, 60));

        nombresText.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        nombresText.setForeground(new java.awt.Color(0, 0, 0));
        nombresText.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nombresText.setText("Nombres");
        jPanel1.add(nombresText, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 60, -1));

        userNameInput.setBackground(new java.awt.Color(255, 255, 255));
        userNameInput.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        userNameInput.setForeground(new java.awt.Color(153, 153, 153));
        userNameInput.setText("Ingrese su nombre de usuario");
        userNameInput.setBorder(null);
        userNameInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userNameInputMousePressed(evt);
            }
        });
        userNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameInputActionPerformed(evt);
            }
        });
        jPanel1.add(userNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 290, 20));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 260, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputActionPerformed

    private void lastNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameInputActionPerformed

    private void addressInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressInputActionPerformed

    private void cityInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityInputActionPerformed

    private void departamentoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departamentoInputActionPerformed

    int xMouse, yMouse;

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        exitBtn.setBackground(Color.red);
    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseExited
        exitBtn.setBackground(Color.white);
    }//GEN-LAST:event_exitBtnMouseExited

    private void goBackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackBtnMouseClicked
        this.setVisible(false);
        setInputToPredetermined();
        Login.getInstance().setVisible(true);
    }//GEN-LAST:event_goBackBtnMouseClicked

    private void goBackBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackBtnMouseEntered
        goBackBtn.setBackground(Color.red);
    }//GEN-LAST:event_goBackBtnMouseEntered

    private void goBackBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackBtnMouseExited
        goBackBtn.setBackground(new Color(75, 181, 255));
    }//GEN-LAST:event_goBackBtnMouseExited

    private void nameInputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameInputMousePressed
        if (nameInput.getText().equals("Ingrese su nombre/s")) {
            nameInput.setText("");
            nameInput.setForeground(Color.black);
        }
        if (String.valueOf(lastNameInput.getText()).isEmpty()) {
            lastNameInput.setText("Ingrese sus apellidos");
            lastNameInput.setForeground(Color.gray);
        }
        if (String.valueOf(addressInput.getText()).isEmpty()) {
            addressInput.setText("Ingrese su dirección");
            addressInput.setForeground(Color.gray);
        }
        if (String.valueOf(cityInput.getText()).isEmpty()) {
            cityInput.setText("Ingrese sus ciudad");
            cityInput.setForeground(Color.gray);
        }
        if (String.valueOf(departamentoInput.getText()).isEmpty()) {
            departamentoInput.setText("Ingrese su departamento");
            departamentoInput.setForeground(Color.gray);
        }
        if (String.valueOf(passwordInput.getText()).isEmpty()) {
            passwordInput.setText("**********");
            passwordInput.setForeground(Color.gray);
        }
        if (String.valueOf(confirmPasswordInput.getText()).isEmpty()) {
            confirmPasswordInput.setText("**********");
            confirmPasswordInput.setForeground(Color.gray);
        }
        if (String.valueOf(userNameInput.getText()).isEmpty()) {
            userNameInput.setText("Ingrese su nombre de usuario");
            userNameInput.setForeground(Color.gray);
        }
    }//GEN-LAST:event_nameInputMousePressed

    private void lastNameInputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastNameInputMousePressed
        if (lastNameInput.getText().equals("Ingrese sus apellidos")) {
            lastNameInput.setText("");
            lastNameInput.setForeground(Color.black);
        }
        if (String.valueOf(nameInput.getText()).isEmpty()) {
            nameInput.setText("Ingrese su nombre/s");
            nameInput.setForeground(Color.gray);
        }
        if (String.valueOf(addressInput.getText()).isEmpty()) {
            addressInput.setText("Ingrese su dirección");
            addressInput.setForeground(Color.gray);
        }
        if (String.valueOf(cityInput.getText()).isEmpty()) {
            cityInput.setText("Ingrese sus ciudad");
            cityInput.setForeground(Color.gray);
        }
        if (String.valueOf(departamentoInput.getText()).isEmpty()) {
            departamentoInput.setText("Ingrese su departamento");
            departamentoInput.setForeground(Color.gray);
        }
        if (String.valueOf(passwordInput.getText()).isEmpty()) {
            passwordInput.setText("**********");
            passwordInput.setForeground(Color.gray);
        }
        if (String.valueOf(confirmPasswordInput.getText()).isEmpty()) {
            confirmPasswordInput.setText("**********");
            confirmPasswordInput.setForeground(Color.gray);
        }
        if (String.valueOf(userNameInput.getText()).isEmpty()) {
            userNameInput.setText("Ingrese su nombre de usuario");
            userNameInput.setForeground(Color.gray);
        }
    }//GEN-LAST:event_lastNameInputMousePressed

    private void addressInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressInputMouseClicked
        if (addressInput.getText().equals("Ingrese su dirección")) {
            addressInput.setText("");
            addressInput.setForeground(Color.black);
        }
        if (String.valueOf(nameInput.getText()).isEmpty()) {
            nameInput.setText("Ingrese su nombre/s");
            nameInput.setForeground(Color.gray);
        }
        if (String.valueOf(lastNameInput.getText()).isEmpty()) {
            lastNameInput.setText("Ingrese sus apellidos");
            lastNameInput.setForeground(Color.gray);
        }
        if (String.valueOf(cityInput.getText()).isEmpty()) {
            cityInput.setText("Ingrese su ciudad");
            cityInput.setForeground(Color.gray);
        }
        if (String.valueOf(departamentoInput.getText()).isEmpty()) {
            departamentoInput.setText("Ingrese su departamento");
            departamentoInput.setForeground(Color.gray);
        }
        if (String.valueOf(passwordInput.getText()).isEmpty()) {
            passwordInput.setText("**********");
            passwordInput.setForeground(Color.gray);
        }
        if (String.valueOf(confirmPasswordInput.getText()).isEmpty()) {
            confirmPasswordInput.setText("**********");
            confirmPasswordInput.setForeground(Color.gray);
        }
        if (String.valueOf(userNameInput.getText()).isEmpty()) {
            userNameInput.setText("Ingrese su nombre de usuario");
            userNameInput.setForeground(Color.gray);
        }
    }//GEN-LAST:event_addressInputMouseClicked

    private void cityInputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cityInputMousePressed
        if (cityInput.getText().equals("Ingrese su ciudad")) {
            cityInput.setText("");
            cityInput.setForeground(Color.black);
        }
        if (String.valueOf(nameInput.getText()).isEmpty()) {
            nameInput.setText("Ingrese su nombre/s");
            nameInput.setForeground(Color.gray);
        }
        if (String.valueOf(lastNameInput.getText()).isEmpty()) {
            lastNameInput.setText("Ingrese sus apellidos");
            lastNameInput.setForeground(Color.gray);
        }
        if (String.valueOf(addressInput.getText()).isEmpty()) {
            addressInput.setText("Ingrese su dirección");
            addressInput.setForeground(Color.gray);
        }
        if (String.valueOf(departamentoInput.getText()).isEmpty()) {
            departamentoInput.setText("Ingrese su departamento");
            departamentoInput.setForeground(Color.gray);
        }
        if (String.valueOf(passwordInput.getText()).isEmpty()) {
            passwordInput.setText("**********");
            passwordInput.setForeground(Color.gray);
        }
        if (String.valueOf(confirmPasswordInput.getText()).isEmpty()) {
            confirmPasswordInput.setText("**********");
            confirmPasswordInput.setForeground(Color.gray);
        }
        if (String.valueOf(userNameInput.getText()).isEmpty()) {
            userNameInput.setText("Ingrese su nombre de usuario");
            userNameInput.setForeground(Color.gray);
        }
    }//GEN-LAST:event_cityInputMousePressed

    private void departamentoInputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departamentoInputMousePressed
        if (departamentoInput.getText().equals("Ingrese su departamento")) {
            departamentoInput.setText("");
            departamentoInput.setForeground(Color.black);
        }
        if (String.valueOf(nameInput.getText()).isEmpty()) {
            nameInput.setText("Ingrese su nombre/s");
            nameInput.setForeground(Color.gray);
        }
        if (String.valueOf(lastNameInput.getText()).isEmpty()) {
            lastNameInput.setText("Ingrese sus apellidos");
            lastNameInput.setForeground(Color.gray);
        }
        if (String.valueOf(addressInput.getText()).isEmpty()) {
            addressInput.setText("Ingrese su dirección");
            addressInput.setForeground(Color.gray);
        }
        if (String.valueOf(cityInput.getText()).isEmpty()) {
            cityInput.setText("Ingrese su ciudad");
            cityInput.setForeground(Color.gray);
        }
        if (String.valueOf(passwordInput.getText()).isEmpty()) {
            passwordInput.setText("**********");
            passwordInput.setForeground(Color.gray);
        }
        if (String.valueOf(confirmPasswordInput.getText()).isEmpty()) {
            confirmPasswordInput.setText("**********");
            confirmPasswordInput.setForeground(Color.gray);
        }
        if (String.valueOf(userNameInput.getText()).isEmpty()) {
            userNameInput.setText("Ingrese su nombre de usuario");
            userNameInput.setForeground(Color.gray);
        }
    }//GEN-LAST:event_departamentoInputMousePressed

    private void passwordInputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordInputMousePressed
        if (passwordInput.getText().equals("**********")) {
            passwordInput.setText("");
            passwordInput.setForeground(Color.black);
        }
        if (String.valueOf(nameInput.getText()).isEmpty()) {
            nameInput.setText("Ingrese su nombre/s");
            nameInput.setForeground(Color.gray);
        }
        if (String.valueOf(lastNameInput.getText()).isEmpty()) {
            lastNameInput.setText("Ingrese sus apellidos");
            lastNameInput.setForeground(Color.gray);
        }
        if (String.valueOf(addressInput.getText()).isEmpty()) {
            addressInput.setText("Ingrese su dirección");
            addressInput.setForeground(Color.gray);
        }
        if (String.valueOf(cityInput.getText()).isEmpty()) {
            cityInput.setText("Ingrese su ciudad");
            cityInput.setForeground(Color.gray);
        }
        if (String.valueOf(departamentoInput.getText()).isEmpty()) {
            departamentoInput.setText("Ingrese su departamento");
            departamentoInput.setForeground(Color.gray);
        }
        if (String.valueOf(confirmPasswordInput.getText()).isEmpty()) {
            confirmPasswordInput.setText("**********");
            confirmPasswordInput.setForeground(Color.gray);
        }
        if (String.valueOf(userNameInput.getText()).isEmpty()) {
            userNameInput.setText("Ingrese su nombre de usuario");
            userNameInput.setForeground(Color.gray);
        }
    }//GEN-LAST:event_passwordInputMousePressed

    private void confirmPasswordInputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPasswordInputMousePressed
        if (confirmPasswordInput.getText().equals("**********")) {
            confirmPasswordInput.setText("");
            confirmPasswordInput.setForeground(Color.black);
        }
        if (String.valueOf(nameInput.getText()).isEmpty()) {
            nameInput.setText("Ingrese su nombre/s");
            nameInput.setForeground(Color.gray);
        }
        if (String.valueOf(lastNameInput.getText()).isEmpty()) {
            lastNameInput.setText("Ingrese sus apellidos");
            lastNameInput.setForeground(Color.gray);
        }
        if (String.valueOf(addressInput.getText()).isEmpty()) {
            addressInput.setText("Ingrese su dirección");
            addressInput.setForeground(Color.gray);
        }
        if (String.valueOf(cityInput.getText()).isEmpty()) {
            cityInput.setText("Ingrese su ciudad");
            cityInput.setForeground(Color.gray);
        }
        if (String.valueOf(departamentoInput.getText()).isEmpty()) {
            departamentoInput.setText("Ingrese su departamento");
            departamentoInput.setForeground(Color.gray);
        }
        if (String.valueOf(passwordInput.getText()).isEmpty()) {
            passwordInput.setText("**********");
            passwordInput.setForeground(Color.gray);
        }
        if (String.valueOf(userNameInput.getText()).isEmpty()) {
            userNameInput.setText("Ingrese su nombre de usuario");
            userNameInput.setForeground(Color.gray);
        }
    }//GEN-LAST:event_confirmPasswordInputMousePressed

    private void continueBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueBtnMouseClicked
        String inputNombres = nameInput.getText();
        String inputApellidos = lastNameInput.getText();
        String inputDireccion = addressInput.getText();
        String inputCiudad = cityInput.getText();
        String inputDepartamento = departamentoInput.getText();
        String inputContrasena = passwordInput.getText();
        String inputConfirmContrasena = confirmPasswordInput.getText();
        String inputUserName = userNameInput.getText();

        if (inputNombres.equals("Ingrese su nombre/s") || inputApellidos.equals("Ingrese sus apellidos")
                || inputDireccion.equals("Ingrese su dirección") || inputDepartamento.equals("Ingrese su departamento")
                || inputCiudad.equals("Ingrese su ciudad") || inputContrasena.equals("**********") || inputConfirmContrasena.equals("**********") || inputUserName.equals("Ingrese su nombre de usuario")) {
            inputNombres = "";
            inputUserName = "";
            inputApellidos = "";
            inputDireccion = "";
            inputCiudad = "";
            inputDepartamento = "";
            inputContrasena = "";
            inputConfirmContrasena = "";
        }

        if (inputApellidos.isEmpty() | inputNombres.isEmpty() | inputCiudad.isEmpty() | inputContrasena.isEmpty() | inputDepartamento.isEmpty() | inputDireccion.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los formularios deben ser completados.");
        } else if (inputContrasena.length() < 6) {
            JOptionPane.showMessageDialog(null, "La contraseña debe tener al menos 6 carácteres.");
        } else {

            Argon2 argon2 = Argon2Factory.create(Argon2Factory.Argon2Types.ARGON2id, 32, 64);

            Random rand = new Random();
            int userID = rand.nextInt(Integer.MAX_VALUE);

            Connection connection = DBConnection.getInstance().dbConnection;

            Statement statement = null;
            boolean usernameAvailable = false;

            ArrayList<String> usernames = new ArrayList<>();

            try {
                statement = connection.createStatement();
                if (statement != null) {
                    String sqlString ="SELECT * FROM [GET_USERNAMES]";
                    var res = statement.executeQuery(sqlString);
                    while (res.next()) {
                        String username = res.getString("nombre_usuario");
                        usernames.add(username);
                    }
                    if (!usernames.contains(inputUserName)) {
                        usernameAvailable = true;
                    } else {
                        JOptionPane.showMessageDialog(null, "El nombre de usuario ya esta siendo utilizado, eliga otro.");
                    }

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al agregar usuario, error: " + e.toString());
            }
            
            if (usernameAvailable) {
                try {
                    if (inputContrasena.equals(inputConfirmContrasena)) {
                        var hashPass = argon2.hash(2, 15 * 1024, 1, inputContrasena.toCharArray());

                        statement = connection.createStatement();
                        if (statement != null) {
                            String sqlString = "INSERT INTO PERSONAS (user_id, nombres, apellidos, direccion, ciudad, departamento, hashpwd, nombre_usuario) "
                                    + "VALUES (" + userID + ", '" + inputNombres.toString() + "', '" + inputApellidos.toString() + "', '"
                                    + inputDireccion.toString() + "', '" + inputCiudad.toString() + "', '" + inputDepartamento.toString() + "', '"
                                    + hashPass.toString() + "', '" + inputUserName.toString() + "')";
                            int rs = statement.executeUpdate(sqlString);
                            if (rs == 1) {
                                UserAccount.getInstance().setUserId(userID);
                                this.setVisible(false);
                                setInputToPredetermined();
                                RegisterQuestions.getInstance().setVisible(true);
                            } else {
                                JOptionPane.showMessageDialog(null, "Problema al agregar el usuario. Prueba otra vez.");
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Contraseñas ingresadas no coinciden");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error al agregar usuario, error: " + e.toString());
                }
            }
        }
    }//GEN-LAST:event_continueBtnMouseClicked

    private void setInputToPredetermined(){
        userNameInput.setText("Ingrese su nombre de usuario");
        nameInput.setText("Ingrese su nombre/s");
        lastNameInput.setText("Ingrese sus apellidos");
        addressInput.setText("Ingrese su dirección");
        cityInput.setText("Ingrese su ciudad");
        departamentoInput.setText("Ingrese su departamento");
        passwordInput.setText("**********");
        confirmPasswordInput.setText("**********");
        
        userNameInput.setForeground(Color.gray);
        nameInput.setForeground(Color.gray);
        lastNameInput.setForeground(Color.gray);
        addressInput.setForeground(Color.gray);
        cityInput.setForeground(Color.gray);
        departamentoInput.setForeground(Color.gray);
        passwordInput.setForeground(Color.gray);
        confirmPasswordInput.setForeground(Color.gray);
    }
    
    private void userNameInputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameInputMousePressed
        if (userNameInput.getText().equals("Ingrese su nombre de usuario")) {
            userNameInput.setText("");
            userNameInput.setForeground(Color.black);
        }
        if (String.valueOf(nameInput.getText()).isEmpty()) {
            nameInput.setText("Ingrese su nombre/s");
            nameInput.setForeground(Color.gray);
        }
        if (String.valueOf(lastNameInput.getText()).isEmpty()) {
            lastNameInput.setText("Ingrese sus apellidos");
            lastNameInput.setForeground(Color.gray);
        }
        if (String.valueOf(addressInput.getText()).isEmpty()) {
            addressInput.setText("Ingrese su dirección");
            addressInput.setForeground(Color.gray);
        }
        if (String.valueOf(cityInput.getText()).isEmpty()) {
            cityInput.setText("Ingrese su ciudad");
            cityInput.setForeground(Color.gray);
        }
        if (String.valueOf(departamentoInput.getText()).isEmpty()) {
            departamentoInput.setText("Ingrese su departamento");
            departamentoInput.setForeground(Color.gray);
        }
        if (String.valueOf(passwordInput.getText()).isEmpty()) {
            passwordInput.setText("**********");
            passwordInput.setForeground(Color.gray);
        }
        if (String.valueOf(confirmPasswordInput.getText()).isEmpty()) {
            confirmPasswordInput.setText("**********");
            confirmPasswordInput.setForeground(Color.gray);
        }
    }//GEN-LAST:event_userNameInputMousePressed

    private void userNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameInputActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressInput;
    private javax.swing.JLabel apellidosText;
    private javax.swing.JLabel bgImage;
    private javax.swing.JTextField cityInput;
    private javax.swing.JLabel ciudadText;
    private javax.swing.JPasswordField confirmPasswordInput;
    private javax.swing.JLabel confirmPasswordText;
    private javax.swing.JPanel continueBtn;
    private javax.swing.JLabel continueTxt;
    private javax.swing.JLabel contraseñaText;
    private javax.swing.JTextField departamentoInput;
    private javax.swing.JLabel departamentoText;
    private javax.swing.JLabel direccionText;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel goBackBtn;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nombreUsuarioText;
    private javax.swing.JLabel nombresText;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JTextField userNameInput;
    // End of variables declaration//GEN-END:variables
}
