/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz_gráfica;

import UserAccount.UserAccount;
import db_connection.DBConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author juan-
 */
public class RolesView extends javax.swing.JFrame {

    /**
     * Creates new form RolesView
     */
    public static RolesView instance;
    private Map<String, Integer> aplicativosId;
    private Map<String, Integer> rolesId;

    public static RolesView getInstance() {
        if (instance == null) {
            instance = new RolesView();
        }
        return instance;
    }

    public RolesView() {
        initComponents();
        Connection connection = DBConnection.getInstance().dbConnection;
        Statement statement = null;

        try {
            statement = connection.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al crear statement, error: " + e.toString());
        }

        aplicativosId = new HashMap<String, Integer>();

        if (statement != null) {
            try {
                String sqlString = "SELECT * "
                        + "FROM APLICATIVOS";
                var res = statement.executeQuery(sqlString);
                while (res.next()) {
                    String nombre_app = res.getString("nombre_app");
                    Integer app_id = res.getInt("app_id");
                    aplicativosId.put(nombre_app, app_id);
                }
                aplicativos.setModel(new DefaultComboBoxModel<String>(aplicativosId.keySet().toArray(new String[0])));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al obtener user, error: " + e.toString());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        goBackBtn = new javax.swing.JPanel();
        goBackTxt = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        aplicativos = new javax.swing.JComboBox<>();
        aplicativoTxt = new javax.swing.JLabel();
        rolesTxt = new javax.swing.JLabel();
        roles = new javax.swing.JComboBox<>();
        solicitarBtn = new javax.swing.JPanel();
        solicitarTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 570));
        setUndecorated(true);
        setResizable(false);
        setSize(getPreferredSize());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan-\\OneDrive - Universidad Católica del Uruguay\\UCU\\2do\\2do semestre\\BD I\\bd-obligatorio\\Autoregistro_Usuarios\\src\\main\\java\\com\\images\\fondoViewRoles.jpg")); // NOI18N
        bg.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 570));

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnMouseExited(evt);
            }
        });

        exitTxt.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        exitTxt.setForeground(new java.awt.Color(0, 0, 0));
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, 40));

        goBackBtn.setBackground(new java.awt.Color(255, 255, 255));
        goBackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                goBackBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                goBackBtnMouseExited(evt);
            }
        });

        goBackTxt.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        goBackTxt.setForeground(new java.awt.Color(0, 0, 0));
        goBackTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goBackTxt.setText("<");

        javax.swing.GroupLayout goBackBtnLayout = new javax.swing.GroupLayout(goBackBtn);
        goBackBtn.setLayout(goBackBtnLayout);
        goBackBtnLayout.setHorizontalGroup(
            goBackBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(goBackTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        goBackBtnLayout.setVerticalGroup(
            goBackBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(goBackTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(goBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 720, 30));

        title.setFont(new java.awt.Font("Calisto MT", 0, 36)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Solicite un rol");
        bg.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 380, 70));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 220, 10));

        aplicativos.setBackground(new java.awt.Color(255, 255, 255));
        aplicativos.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        aplicativos.setForeground(new java.awt.Color(0, 0, 0));
        aplicativos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicativosActionPerformed(evt);
            }
        });
        bg.add(aplicativos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 220, 30));

        aplicativoTxt.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        aplicativoTxt.setForeground(new java.awt.Color(0, 0, 0));
        aplicativoTxt.setText("Seleccione un aplicativo");
        bg.add(aplicativoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 220, 30));

        rolesTxt.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        rolesTxt.setForeground(new java.awt.Color(0, 0, 0));
        rolesTxt.setText("Seleccione un rol");
        bg.add(rolesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 220, 30));

        roles.setBackground(new java.awt.Color(255, 255, 255));
        roles.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        roles.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(roles, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 220, 30));

        solicitarBtn.setBackground(new java.awt.Color(50, 149, 216));
        solicitarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        solicitarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                solicitarBtnMouseClicked(evt);
            }
        });

        solicitarTxt.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        solicitarTxt.setForeground(new java.awt.Color(255, 255, 255));
        solicitarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        solicitarTxt.setText("Solicitar rol");

        javax.swing.GroupLayout solicitarBtnLayout = new javax.swing.GroupLayout(solicitarBtn);
        solicitarBtn.setLayout(solicitarBtnLayout);
        solicitarBtnLayout.setHorizontalGroup(
            solicitarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(solicitarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        solicitarBtnLayout.setVerticalGroup(
            solicitarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(solicitarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        bg.add(solicitarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 180, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        exitBtn.setBackground(Color.red);
    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseExited
        exitBtn.setBackground(Color.white);
    }//GEN-LAST:event_exitBtnMouseExited

    private void goBackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackBtnMouseClicked
        this.setVisible(false);
        Home.getInstance().setVisible(true);
    }//GEN-LAST:event_goBackBtnMouseClicked

    private void goBackBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackBtnMouseEntered
        goBackBtn.setBackground(Color.red);
    }//GEN-LAST:event_goBackBtnMouseEntered

    private void goBackBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackBtnMouseExited
        goBackBtn.setBackground(Color.white);
    }//GEN-LAST:event_goBackBtnMouseExited

    int xMouse, yMouse;
    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void aplicativosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicativosActionPerformed
        Connection connection = DBConnection.getInstance().dbConnection;
        Statement statement = null;

        try {
            statement = connection.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al crear statement, error: " + e.toString());
        }

        rolesId = new HashMap<String, Integer>();

        String chosenAplic = String.valueOf(aplicativos.getSelectedItem());
        int app_Id = aplicativosId.get(chosenAplic);

        if (statement != null) {
            try {
                String sqlString = "SELECT * "
                        + "FROM (SELECT * "
                        + "FROM ROLES_NEGOCIO_APLICATIVOS "
                        + "WHERE app_id=" + app_Id + ") p "
                        + "JOIN ROLES_NEGOCIO "
                        + "ON p.rol_neg_id = ROLES_NEGOCIO.rol_neg_id ";
                var res = statement.executeQuery(sqlString);
                while (res.next()) {
                    Integer rol_neg_id = res.getInt("rol_neg_id");
                    String descripcion_rol_neg = res.getString("descripcion_rol_neg");
                    rolesId.put(descripcion_rol_neg, rol_neg_id);
                }
                roles.setModel(new DefaultComboBoxModel<String>(rolesId.keySet().toArray(new String[0])));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al realizar consulta, error: " + e.toString());
            }
        }
    }//GEN-LAST:event_aplicativosActionPerformed

    private void solicitarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solicitarBtnMouseClicked
        int rol_neg_id = rolesId.get(String.valueOf(roles.getSelectedItem()));
        int app_id = aplicativosId.get(String.valueOf(aplicativos.getSelectedItem()));
        int user_id = UserAccount.getInstance().getUserId();
        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        String strDate = formatter.format(date);

        Connection connection = DBConnection.getInstance().dbConnection;

        Statement statement = null;
        try {
            statement = connection.createStatement();
            if (statement != null) {
                String sqlString = "INSERT INTO PERMISOS (user_id, app_id, rol_neg_id, fecha_solicitud, fecha_autorizacion, estado) "
                        + "VALUES (" + user_id + ", '" + app_id + "', '" + rol_neg_id + "', '"
                        + strDate + "', '" + null + "', '" + "PENDIENTE" + "')";
                int rs = statement.executeUpdate(sqlString);
                if (rs == 1) {
                    JOptionPane.showMessageDialog(null, "Solicitud realizada correctamente.");
                    this.setVisible(false);
                    Home.getInstance().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Problema al solicitar permiso. Prueba otra vez.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error solicitar permiso, error: " + e.toString());
        }
    }//GEN-LAST:event_solicitarBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RolesView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RolesView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RolesView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RolesView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RolesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aplicativoTxt;
    private javax.swing.JComboBox<String> aplicativos;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel goBackBtn;
    private javax.swing.JLabel goBackTxt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel image;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> roles;
    private javax.swing.JLabel rolesTxt;
    private javax.swing.JPanel solicitarBtn;
    private javax.swing.JLabel solicitarTxt;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
